runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: MySQLdb
  version: "latest"

env_variables:
    # Replace user, password, database, project, and instance with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      mysql+mysqldb://ROOT@/cloudbd?unix_socket=/cloudsql/atol-test:us-east1:cloudbd

skip_files:
 - server/lib/flask/ext/setuptools/script\ \(dev\).tmpl
 