runtime: python27
api_version: 1.001
threadsafe: yes

handlers:
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: MySQLdb
  version: "latest"

env_variables:
    SQLALCHEMY_DATABASE_URI: >-
      mysql+mysqldb://root@/atol_hab?unix_socket=/cloudsql/atol-test:us-east1:cloudbd

skip_files:
 - env/lib/python2.7/site-packages/setuptools/script\ \(dev\).tmpl
 - env/local/lib/python2.7/site-packages/setuptools/script\ \(dev\).tmpl
